{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - services
      - pods
      - nodes
      - events
    verbs:
      - get
      - list
      - watch
  {{/* Required for Rollout Restart Attack */}}
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - patch
  {{/* Required for Delete Pod Attack */}}
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - delete
  {{/* Required for Drain/Taint Node Attacks */}}
  - apiGroups: [""]
    resources:
      - pods/eviction
    verbs:
      - create
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - patch
{{- end }}
